version: '3.4'

services:
  studentsapi:
    image: ${DOCKER_REGISTRY-}studentsapi
    container_name: StudentsAPI
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__StudentsAPIContext=Server=sqldata;Database=StudentDB;User Id=sa;Password=Test!@123123
      - MessageBroker__Host=amqp://user:Test123123@rabbitmq:5672
    ports:
      - "5081:80"
    depends_on:
      - sqldata

  coursesapi:
    image: ${DOCKER_REGISTRY-}coursesapi
    container_name: CoursesAPI
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CoursesApiContext=Server=sqldata;Database=CoursesDB;User Id=sa;Password=Test!@123123
      - MessageBroker__Host=amqp://user:Test123123@rabbitmq:5672
    ports:
      - "5082:80"
    depends_on:
      - sqldata

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    container_name: APIGateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5083:80"

  rabbitmq:
      image: rabbitmq:3-management
      container_name: rbtmq
      environment:
          - RABBITMQ_DEFAULT_USER=user
          - RABBITMQ_DEFAULT_PASS=Test123123
      ports:
          - 5672:5672
          - 15672:15672

  sqldata:
     image: mcr.microsoft.com/mssql/server:2019-latest
     environment:
       - SA_PASSWORD=Test!@123123
       - ACCEPT_EULA=Y
     ports:
       - "1433:1433"