apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\RutaAdmin\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe --file docker-compose.yml convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: apigateway
  name: apigateway
spec:
  ports:
    - name: "5083"
      port: 5083
      targetPort: 80
  selector:
    io.kompose.service: apigateway
status:
  loadBalancer: {}
