apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\RutaAdmin\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe --file docker-compose.yml convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: coursesapi
  name: coursesapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: coursesapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\RutaAdmin\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe --file docker-compose.yml convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/studentsapi-default: "true"
        io.kompose.service: coursesapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__CoursesApiContext
              value: Server=sqldata;Database=CoursesDB;User Id=sa;Password=Test!@123123
            - name: MessageBroker__Host
              value: amqp://user:Test123123@rabbitmq:5672
          image: coursesapi
          name: coursesapi
          ports:
            - containerPort: 80
              hostPort: 5082
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
